// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 结构体
type CallRquest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRquest) Reset()         { *m = CallRquest{} }
func (m *CallRquest) String() string { return proto.CompactTextString(m) }
func (*CallRquest) ProtoMessage()    {}
func (*CallRquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CallRquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRquest.Unmarshal(m, b)
}
func (m *CallRquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRquest.Marshal(b, m, deterministic)
}
func (m *CallRquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRquest.Merge(m, src)
}
func (m *CallRquest) XXX_Size() int {
	return xxx_messageInfo_CallRquest.Size(m)
}
func (m *CallRquest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRquest.DiscardUnknown(m)
}

var xxx_messageInfo_CallRquest proto.InternalMessageInfo

func (m *CallRquest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CallResponse struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallResponse) Reset()         { *m = CallResponse{} }
func (m *CallResponse) String() string { return proto.CompactTextString(m) }
func (*CallResponse) ProtoMessage()    {}
func (*CallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResponse.Unmarshal(m, b)
}
func (m *CallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResponse.Marshal(b, m, deterministic)
}
func (m *CallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResponse.Merge(m, src)
}
func (m *CallResponse) XXX_Size() int {
	return xxx_messageInfo_CallResponse.Size(m)
}
func (m *CallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallResponse proto.InternalMessageInfo

func (m *CallResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EmptyRquest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRquest) Reset()         { *m = EmptyRquest{} }
func (m *EmptyRquest) String() string { return proto.CompactTextString(m) }
func (*EmptyRquest) ProtoMessage()    {}
func (*EmptyRquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *EmptyRquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRquest.Unmarshal(m, b)
}
func (m *EmptyRquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRquest.Marshal(b, m, deterministic)
}
func (m *EmptyRquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRquest.Merge(m, src)
}
func (m *EmptyRquest) XXX_Size() int {
	return xxx_messageInfo_EmptyRquest.Size(m)
}
func (m *EmptyRquest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRquest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRquest proto.InternalMessageInfo

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CallRquest)(nil), "CallRquest")
	proto.RegisterType((*CallResponse)(nil), "CallResponse")
	proto.RegisterType((*EmptyRquest)(nil), "EmptyRquest")
	proto.RegisterType((*EmptyResponse)(nil), "EmptyResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0, 0xe2, 0x72, 0x4e, 0xcc, 0xc9, 0x09, 0x2a, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x34, 0xb8, 0x78, 0xc0, 0x2a, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0xc0, 0xca,
	0x60, 0x5c, 0x25, 0x5e, 0x2e, 0x6e, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0x88, 0x61, 0x4a, 0xfc, 0x5c,
	0xbc, 0x10, 0x2e, 0x54, 0xa7, 0x91, 0x3e, 0x17, 0xbb, 0x6b, 0x45, 0x62, 0x6e, 0x41, 0x4e, 0xaa,
	0x90, 0x0a, 0x17, 0x0b, 0xc8, 0x50, 0x21, 0x6e, 0x3d, 0x84, 0xed, 0x52, 0xbc, 0x7a, 0xc8, 0x16,
	0x29, 0x31, 0x18, 0xe9, 0x70, 0x31, 0xbb, 0xe5, 0xe7, 0x0b, 0xa9, 0x72, 0x31, 0x3b, 0x25, 0x16,
	0x09, 0xf1, 0xe8, 0x21, 0x99, 0x2e, 0xc5, 0xa7, 0x87, 0x62, 0xb8, 0x12, 0x43, 0x12, 0x1b, 0xd8,
	0x47, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xbc, 0x87, 0x1d, 0xde, 0x00, 0x00, 0x00,
}
